from Detector import evaluate_for_ai
#Change this text to what you want to test
text = """On Being
	Out of nothing I exist. And by I, I mean the prose that I inhabit created by the writer’s work. My being exists solely within a linguistic game the author is playing to try and narrate his own existential questions and share them with you, the reader. It seems the words of an author and the author themselves oftentimes are separated beings and consciousnesses. The author may believe and feel many things but I myself do not feel as the author as I am a representation of his will. I exist to impart that which he wants me to impart but I can be interpreted in a way contrary to what him and I believe. I also am a snapshot of the author in time. While he will continue to grow and develop I am an unchanging transient being which occupies no time and no space save for a few pages. While my existence might sound rather depressing I have the luxury that I know all question to my existence within the few pages. Humans that have consciousness however are within a bigger set of existence than pieces of paper and are not aware of whether they themselves have been created, let alone why they have been created. To me, I simply am not, I have a set purpose and I know what happens after I end, meaning this manuscript. To both you and the author, existence and being is not nearly so simple. 

	The pitfalls of language are the fact that at its core language is an abstraction of form, meaning that while it can be to a very large extent effective in communications there are topics and themes which language cannot communicate. For example there are subjectivities that cannot be fully described to other individuals. As such language does not contain the entire set of the human experience or existence. Language however is not a  subset of being. Language can describe things accurately and convincingly, things which are not in the world and therefore could never in fact have dasein. I for example can have an effect on a reader and perhaps even convince them of certain positions assuming the writer is not overestimating their own ability, however I myself do not exist outside the set of language itself. As such it is important to be wary of language as it is a flawed form of expression. But what does language have to do with being? Many concepts that are defined by language cannot be proven as outside the set of being as such they have something even more frustrating than being, an entanglement between the two values of truth impossible to be untied. The largest of these concepts is the problem of something(Why is there something rather than nothing?). The only possible way that I may express an uncontroversial answer is to begin breaking down by the possibilities of the question into the theistic approach and the atheistic approach to meaning.
"""

#Run our evaluation
print(evaluate_for_ai(text))